### ISSUE TITLE
Playing back UDP packets on loopback address

### ISSUE THREAD

**Issue by mkilling** [signal11/PlayCap#1]
Is there be a problem with playing back packets that were sent to the loopback address? I have a capture which sends UDP packets to localhost:3000 (captured on a Mac).
I now want to play back that file on a Windows machine. I read something about Wireshark being unable to capture packets to loopback on Windows....
I chose my standard network adapter to play back the packets. Can PlayCap send UDP packets to the loopback address?

**Comment by signal11** [comment]
It may have changed, but last I checked, it was not possible to capture 
packets on a loopback address. This was a limitation of libpcap. I 
assume sending is the same way. Did you try it?

**Comment by mkilling** [comment]
Yes, it didn't work. I wanted to make sure that it wasn't my mistake.
